### ISSUE TITLE
rustack_vm.ip_address attribute

### ISSUE THREAD

**Issue by ruzmuh** [pilat/terraform-provider-rustack#8]
according to terraform provider rustack_vm.ip_address attribute is read_only. But API allows you to set ip_addressfor a new VM. (see https://cp.sbcloud.ru/swagger/#/Servers/post_v1_vm).

Is it possible to make the ip_address attribute optional?

**Comment by pilat** [comment]
Hello, ruzmuh!

Thank you for the MR! It's merged
